Repository koordinator-sh/website, pull requests merged in 2022-08, with the labels that each got.

#70 add user manual for resource-reservation
  docs/designs/resource-reservation.md
  docs/user-manuals/fine-grained-cpu-orchestration.md
  docs/user-manuals/resource-reservation.md
  sidebars.js
  static/img/resource-reservation.svg
Labels: approved, lgtm, size/XL

#69 update typo of config key with QOS and lsClass
  blog/2022-05-07-release/index.md
  blog/2022-05-31-release/index.md
Labels: approved, lgtm, size/S

#50 add more installation dependency description
  docs/installation.md
Labels: size/XS, approved, lgtm

#72 add PodMigrationJob user-manual docs and PodMigrationJob, descheduler…
  docs/designs/descheduler-framework.md
  docs/designs/pod-migration-job.md
  docs/user-manuals/pod-migration-job.md
  sidebars.js
Labels: size/XL

#73 add v0.6.0 release note
  blog/2022-08-04-release/index.md
  docs/installation.md
Labels: size/L

#71 fix comma typo
  blog/2022-05-07-release/index.md
Labels: size/XS, approved, lgtm

#74 release v0.6
  blog/2022-08-04-release/index.md
  versioned_docs/version-v0.6/architecture/overview.md
  versioned_docs/version-v0.6/architecture/priority.md
  versioned_docs/version-v0.6/architecture/qos.md
  versioned_docs/version-v0.6/architecture/resource-model.md
  versioned_docs/version-v0.6/best-practices/colocation-of-spark-jobs.md
  versioned_docs/version-v0.6/designs/descheduler-framework.md
  versioned_docs/version-v0.6/designs/fine-grained-cpu-orchestration.md
  versioned_docs/version-v0.6/designs/koordlet-overview.md
  versioned_docs/version-v0.6/designs/load-aware-scheduling.md
  versioned_docs/version-v0.6/designs/pod-migration-job.md
  versioned_docs/version-v0.6/designs/resource-reservation.md
  versioned_docs/version-v0.6/designs/runtime-proxy.md
  versioned_docs/version-v0.6/installation.md
  versioned_docs/version-v0.6/introduction.md
  versioned_docs/version-v0.6/user-manuals/colocation-profile.md
  versioned_docs/version-v0.6/user-manuals/fine-grained-cpu-orchestration.md
  versioned_docs/version-v0.6/user-manuals/load-aware-scheduling.md
  versioned_docs/version-v0.6/user-manuals/pod-migration-job.md
  versioned_docs/version-v0.6/user-manuals/resource-reservation.md
  versioned_sidebars/version-v0.6-sidebars.json
  versions.json
Labels: size/XXL

#75 add cpu suppress doc
  docs/user-manuals/cpu-suppress.md
  sidebars.js
  static/img/cpu-suppress-demo.svg
Labels: approved, size/L, lgtm

#76 fix cpu qos typo
  blog/2022-05-31-release/index.md
Labels: size/XS, approved, lgtm

#77 add PreCreateContainer to proxy default conf
  docs/designs/runtime-proxy.md
  versioned_docs/version-v0.6/designs/runtime-proxy.md
Labels: size/XS, approved, lgtm

#78 fix comma typo
  versioned_docs/version-v0.6/designs/runtime-proxy.md
Labels: size/XS

#79 improve installation docs for koord-runtime-proxy
  docs/installation.md
  versioned_docs/version-v0.6/installation.md
Labels: approved, size/L, lgtm

#80 fix arch pic
  static/img/what-is-koordinator.svg
Labels: size/XS, approved, lgtm
