Repository koordinator-sh/website, pull requests merged in 2022-11, with the labels that each got.

#97 Update installation.md
  docs/installation.md
Labels: size/XS, approved, lgtm

#98 add release v1.0 blog and update installation
  blog/2022-11-03-release/index.md
  docs/installation.md
Labels: size/M, approved, lgtm

#93 Translate i18n/zh-Hans/docusaurus-plugin-content-docs/current/introduction.md i18n/zh-Hans/docusaurus-plugin-content-docs/current/installation.md
  README-zh.md
  README.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/installation.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/introduction.md
Labels: approved, size/L, lgtm

#101 release 1.0
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0.json
  versioned_docs/version-v1.0/architecture/overview.md
  versioned_docs/version-v1.0/architecture/priority.md
  versioned_docs/version-v1.0/architecture/qos.md
  versioned_docs/version-v1.0/architecture/resource-model.md
  versioned_docs/version-v1.0/best-practices/colocation-of-spark-jobs.md
  versioned_docs/version-v1.0/designs/descheduler-framework.md
  versioned_docs/version-v1.0/designs/fine-grained-cpu-orchestration.md
  versioned_docs/version-v1.0/designs/fine-grained-device-scheduling.md
  versioned_docs/version-v1.0/designs/gang-scheduling.md
  versioned_docs/version-v1.0/designs/koordlet-overview.md
  versioned_docs/version-v1.0/designs/load-aware-scheduling.md
  versioned_docs/version-v1.0/designs/multi-hierarchy-elastic-quota-management.md
  versioned_docs/version-v1.0/designs/pod-migration-job.md
  versioned_docs/version-v1.0/designs/resource-reservation.md
  versioned_docs/version-v1.0/designs/runtime-proxy.md
  versioned_docs/version-v1.0/installation.md
  versioned_docs/version-v1.0/introduction.md
  versioned_docs/version-v1.0/user-manuals/colocation-profile.md
  versioned_docs/version-v1.0/user-manuals/cpu-burst.md
  versioned_docs/version-v1.0/user-manuals/cpu-suppress.md
  versioned_docs/version-v1.0/user-manuals/fine-grained-cpu-orchestration.md
  versioned_docs/version-v1.0/user-manuals/fine-grained-device-scheduling.md
  versioned_docs/version-v1.0/user-manuals/gang-scheduling.md
  versioned_docs/version-v1.0/user-manuals/load-aware-scheduling.md
  versioned_docs/version-v1.0/user-manuals/multi-hierarchy-elastic-quota-management.md
  versioned_docs/version-v1.0/user-manuals/pod-migration-job.md
  versioned_docs/version-v1.0/user-manuals/resource-reservation.md
  versioned_sidebars/version-v1.0-sidebars.json
  versions.json
Labels: size/XXL, approved, lgtm

#100 user manuals: add memory qos doc
  docs/user-manuals/memory-qos.md
  sidebars.js
  static/img/memory-qos.png
Labels: approved, size/L, lgtm

#103 Translaten i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/load-aware-scheduling
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/load-aware-scheduling.md
Labels: size/M, approved, lgtm

#104 Fix docs structure for zh-Hans and add notes into README
  README-zh.md
  README.md
  docusaurus.config.js
  i18n/zh-Hans/docusaurus-plugin-content-docs/current.json
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v0.5.json
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v0.6.json
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v0.7.json
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0.json
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/architecture/overview.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/architecture/priority.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/architecture/qos.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/architecture/resource-model.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/best-practices/colocation-of-spark-jobs.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/descheduler-framework.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/fine-grained-cpu-orchestration.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/fine-grained-device-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/gang-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/koordlet-overview.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/load-aware-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/multi-hierarchy-elastic-quota-management.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/pod-migration-job.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/resource-reservation.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/runtime-proxy.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/installation.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/introduction.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/colocation-profile.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/cpu-suppress.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/fine-grained-cpu-orchestration.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/fine-grained-device-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/gang-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/load-aware-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/multi-hierarchy-elastic-quota-management.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/pod-migration-job.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/resource-reservation.md
  package-lock.json
  versioned_sidebars/version-v1.0-sidebars.json
  yarn.lock
Labels: size/XXL, approved, lgtm

#99 Translaten i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/gang-scheduling
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/gang-scheduling.md
Labels: size/M, approved, lgtm

#95 Translaten i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/koordlet-overview
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/koordlet-overview.md
Labels: size/M, approved, lgtm

#92 Feat translate arch overview
  docs/architecture/overview.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/architecture/overview.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/architecture/priority.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/architecture/qos.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/architecture/resource-model.md
Labels: approved, size/L, lgtm

#105 add design docs/enhanced scheduler extension
  docs/designs/enhanced-scheduler-extension.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/enhanced-scheduler-extension.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/enhanced-scheduler-extension.md
  sidebars.js
  static/img/scheduler-extension.jpg
  versioned_docs/version-v1.0/designs/enhanced-scheduler-extension.md
  versioned_sidebars/version-v1.0-sidebars.json
Labels: approved, lgtm, size/XL

#96 Translaten i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/runtime-proxy
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/runtime-proxy.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/runtime-proxy.md
Labels: approved, size/L, lgtm

#106 Feat to version 1.0
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/architecture/overview.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/architecture/priority.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/architecture/qos.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/architecture/resource-model.md
Labels: approved, size/L, lgtm

#107 zh koordlet load awre 1.0
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/koordlet-overview.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/load-aware-scheduling.md
Labels: approved, size/L, lgtm

#109 update gang-scheduling to version 1.0
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/gang-scheduling.md
Labels: size/M, approved, lgtm

#108 update scheduler extension image
  static/img/scheduler-extension.jpg
Labels: size/XS, approved, lgtm
