Repository koordinator-sh/website, pull requests merged in 2022-06, with the labels that each got.

#52 update release note and installation doc
  blog/2022-05-31-release/index.md
  docs/installation.md
Labels: size/M, approved, lgtm

#55 update installation doc with v0.4.1
  docs/installation.md
Labels: size/XS, approved, lgtm

#56 release 0.4
  versioned_docs/version-v0.4/best-practices/colocation-of-spark-jobs.md
  versioned_docs/version-v0.4/installation.md
  versioned_docs/version-v0.4/introduction.md
  versioned_docs/version-v0.4/key-designs/koordlet-overview.md
  versioned_docs/version-v0.4/key-designs/overview.md
  versioned_docs/version-v0.4/key-designs/priority.md
  versioned_docs/version-v0.4/key-designs/qos.md
  versioned_docs/version-v0.4/key-designs/resource-model.md
  versioned_docs/version-v0.4/user-manuals/colocation-profile.md
  versioned_sidebars/version-v0.4-sidebars.json
  versions.json
Labels: size/XS
