Repository koordinator-sh/website, pull requests merged in 2022-10, with the labels that each got.

#84 add gang\gpu\quota
  docs/designs/fine-grained-device-scheduling.md
  docs/designs/gang-scheduling.md
  docs/designs/multi-hierarchy-elastic-quota-management.md
  docs/user-manuals/fine-grained-device-scheduling.md
  docs/user-manuals/gang-scheduling.md
  docs/user-manuals/multi-hierarchy-elastic-quota-management.md
  static/img/nvlink.jpg
  static/img/quotaguarantee1.jpg
  static/img/quotaguarantee2.jpg
  static/img/quotatree.jpg
  static/img/quotatree1.jpg
  static/img/quotatree2.jpg
  static/img/quotatree3.jpg
  static/img/quotatree4.jpg
  static/img/runtimequota1.jpg
  static/img/runtimequota2.jpg
  static/img/runtimequota3.jpg
  static/img/runtimequota4.jpg
Labels: size/XXL, approved, lgtm

#87 bugfix kubelet runtime parameters example
  docs/designs/runtime-proxy.md
  docs/installation.md
  versioned_docs/version-v0.7/designs/runtime-proxy.md
  versioned_docs/version-v0.7/installation.md
Labels: approved, lgtm, size/S

#88 fix memory qos blog
  blog/2022-05-07-release/index.md
Labels: approved, lgtm, size/S

#89 Initialize i18n
  docusaurus.config.js
  i18n/zh-Hans/code.json
  i18n/zh-Hans/docusaurus-plugin-content-blog/options.json
  i18n/zh-Hans/docusaurus-plugin-content-docs/current.json
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/architecture/overview.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/architecture/priority.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/architecture/qos.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/architecture/resource-model.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/best-practices/colocation-of-spark-jobs.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/descheduler-framework.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/fine-grained-cpu-orchestration.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/fine-grained-device-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/gang-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/koordlet-overview.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/load-aware-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/multi-hierarchy-elastic-quota-management.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/pod-migration-job.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/resource-reservation.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/runtime-proxy.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/installation.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/introduction.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/colocation-profile.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/cpu-suppress.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/fine-grained-cpu-orchestration.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/fine-grained-device-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/gang-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/load-aware-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/multi-hierarchy-elastic-quota-management.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/pod-migration-job.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/resource-reservation.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v0.5.json
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v0.6.json
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v0.7.json
  i18n/zh-Hans/docusaurus-theme-classic/footer.json
  i18n/zh-Hans/docusaurus-theme-classic/navbar.json
  src/components/features.js
  src/pages/index.js
Labels: size/XXL, approved, lgtm

#94 user manuals: add cpu burst doc
  docs/user-manuals/cpu-burst.md
  sidebars.js
  static/img/cpu-throttles-1.png
  static/img/cpu-throttles-2.png
  static/img/cpu-throttles.png
Labels: approved, size/L, lgtm
