Repository koordinator-sh/website, pull requests merged in 2022-05, with the labels that each got.

#43 added functionality diagram
  src/components/features.js
  static/img/resource-isolation-feature.svg
  static/img/resource-model-feature.svg
  static/img/undraw_docusaurus_mountain.svg
  static/img/undraw_docusaurus_react.svg
  static/img/undraw_docusaurus_tree.svg
  static/img/workloads-orchestration-feature.svg
Labels: approved, size/L, lgtm

#44 Fix svg text export problems
  static/img/resource-isolation-feature.svg
Labels: size/XS, approved, lgtm

#45 Improve ClusterColocationProfile doc
  docs/user-manuals/colocation-profile.md
  static/img/clustercolocationprofile-arch.png
Labels: approved, size/L, lgtm

#46 📖 update release notes for v0.3.0
  .gitignore
  blog/2022-05-07-release/index.md
  blog/authors.yml
  docs/installation.md
Labels: approved, size/L, lgtm

#47 Add version v0.3
  versioned_docs/version-v0.3/best-practices/colocation-of-spark-jobs.md
  versioned_docs/version-v0.3/installation.md
  versioned_docs/version-v0.3/introduction.md
  versioned_docs/version-v0.3/key-designs/koordlet-overview.md
  versioned_docs/version-v0.3/key-designs/overview.md
  versioned_docs/version-v0.3/key-designs/priority.md
  versioned_docs/version-v0.3/key-designs/qos.md
  versioned_docs/version-v0.3/key-designs/resource-model.md
  versioned_docs/version-v0.3/user-manuals/colocation-profile.md
  versioned_sidebars/version-v0.3-sidebars.json
  versions.json
Labels: approved, lgtm, size/XL

#48 Fix 0.3 sidebar
  versioned_sidebars/version-v0.3-sidebars.json
Labels: size/XS, approved, lgtm

#49 update architecture diagram
  static/img/architecture.png
Labels: size/XS, approved, lgtm
