Repository koordinator-sh/website, pull requests merged in 2022-12, with the labels that each got.

#115 update CPU orcheration and add CPU image
  docs/architecture/qos.md
  docs/designs/fine-grained-cpu-orchestration.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/architecture/qos.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/fine-grained-cpu-orchestration.md
  static/img/qos-cpu-orchestration.png
Labels: size/M, approved, lgtm

#111 Translaten i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/fine-grained-cpu-orchestration
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/fine-grained-cpu-orchestration.md
Labels: approved, size/L, lgtm

#110 translate gang-scheduling design
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/gang-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/gang-scheduling.md
Labels: approved, lgtm, size/XL

#102 Translaten i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/load-aware-scheduling.md
  .gitignore
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/colocation-profile.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/load-aware-scheduling.md
Labels: approved, size/L, lgtm

#116 update i18n version v1.0 with colocationProfile and load-aware-scheduling
  docs/user-manuals/colocation-profile.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/colocation-profile.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/load-aware-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/colocation-profile.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/load-aware-scheduling.md
Labels: approved, size/L, lgtm
