Repository koordinator-sh/website, pull requests merged in 2022-03, with the labels that each got.

#1 Add document directory structure
  docs/best-practices/colocation-of-spark-jobs.md
  docs/core-concepts/architecture.md
  docs/core-concepts/priority.md
  docs/core-concepts/qos.md
  docs/installation.md
  docs/introduction.md
  docs/user-manuals/colocation-profile.md
  docusaurus.config.js
  package-lock.json
  package.json
  sidebars.js
  src/components/HomepageFeatures/index.js
  yarn.lock
Labels: size/XXL

#2 remove intro.md
  OWNERS
  docs/intro.md
  docusaurus.config.js
Labels: size/M

#3 fix baseUrl of docusaurus
  docusaurus.config.js
Labels: size/XS

#5 add architecture doc
  docs/core-concepts/architecture.md
  static/img/architecture.png
Labels: size/M, approved

#6 add core-concepts of colocation in koordinator
  docs/core-concepts/architecture.md
  docs/core-concepts/priority.md
  docs/core-concepts/qos.md
  docs/core-concepts/resource-model.md
  sidebars.js
  static/img/resource-model.png
Labels: approved, size/L, lgtm

#7 update installation.md
  docs/installation.md
Labels: approved, size/L, lgtm

#9 Add CNAME file
  static/CNAME
Labels: size/XS, approved, lgtm

#10 optimize installation page
  docs/installation.md
Labels: approved, lgtm, size/S

#11 optimize installation page
  docs/installation.md
Labels: size/XS, approved, lgtm

#12 add colocation profile doc
  docs/user-manuals/colocation-profile.md
Labels: size/M, approved, lgtm

#16 fix architecture image
  static/img/architecture.png
Labels: size/XS, approved, lgtm

#13 add spark tutorial
  docs/best-practices/colocation-of-spark-jobs.md
Labels: size/M, approved, lgtm

#18 fix typo
  docs/core-concepts/architecture.md
Labels: size/XS, approved, lgtm

#19 Update colocation-profile.md
  docs/user-manuals/colocation-profile.md
Labels: size/XS, approved

#20 add contributing section in README.md
  README.md
Labels: size/M, approved, lgtm

#21 add Getting Started Link in home page
  src/pages/index.js
  src/pages/index.module.css
Labels: size/M, approved, lgtm

#22 add koordinator v0.1.0 release note
  blog/2019-05-28-first-blog-post.md
  blog/2019-05-29-long-blog-post.md
  blog/2021-08-01-mdx-blog-post.mdx
  blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  blog/2021-08-26-welcome/index.md
  blog/2022-03-31-release/index.md
  blog/authors.yml
Labels: approved, size/L, lgtm

#23 fix release uri
  blog/2022-03-31-release/index.md
Labels: size/XS, approved, lgtm

#24 Fix releasenotes
  blog/2022-03-31-release/index.md
  docusaurus.config.js
Labels: size/XS, approved, lgtm
