Repository koordinator-sh/website, pull requests merged in 2022-04, with the labels that each got.

#25 update installation doc
  blog/2022-03-31-release/index.md
  docs/best-practices/colocation-of-spark-jobs.md
  docs/installation.md
Labels: approved, lgtm, size/S

#26 Fix typo of "scheduler"
  docs/introduction.md
Labels: size/XS, approved, lgtm

#27 update logo & add some links
  docusaurus.config.js
  src/css/custom.css
  static/img/favicon.ico
  static/img/logo.svg
Labels: size/M, approved, lgtm

#28 Typo fixing
  docs/best-practices/colocation-of-spark-jobs.md
  docs/core-concepts/architecture.md
  docs/core-concepts/priority.md
  docs/core-concepts/qos.md
  docs/user-manuals/colocation-profile.md
Labels: size/M, approved, lgtm

#31 adjust the color of the page
  docusaurus.config.js
  src/css/custom.css
  src/pages/index.js
  src/pages/index.module.css
  static/img/favicon.ico
Labels: size/M, approved, lgtm

#33 Update resource-model.md
  docs/core-concepts/resource-model.md
Labels: size/XS

#32 add release-0.2.0 note and update installation doc
  blog/2022-04-19-release/index.md
  docs/installation.md
Labels: approved, size/L, lgtm

#34 update release note v0.2.0
  blog/2022-04-19-release/index.md
Labels: size/XS, approved, lgtm

#37 add versioned docs
  docusaurus.config.js
  versioned_docs/version-v0.2/best-practices/colocation-of-spark-jobs.md
  versioned_docs/version-v0.2/core-concepts/architecture.md
  versioned_docs/version-v0.2/core-concepts/priority.md
  versioned_docs/version-v0.2/core-concepts/qos.md
  versioned_docs/version-v0.2/core-concepts/resource-model.md
  versioned_docs/version-v0.2/installation.md
  versioned_docs/version-v0.2/introduction.md
  versioned_docs/version-v0.2/user-manuals/colocation-profile.md
  versions.json
Labels: approved, lgtm, size/XL

#42 Fix 38
  src/components/HomepageFeatures/index.js
  src/components/HomepageFeatures/styles.module.css
  src/components/features.js
  src/css/custom.css
  src/pages/index.js
  src/pages/index.module.css
  src/pages/markdown-page.md
  static/img/logo-w.svg
  static/img/what-is-koordinator.svg
Labels: size/XXL, approved, lgtm
