Repository koordinator-sh/website, pull requests merged in 2022-07, with the labels that each got.

#59 add user manual for load-aware-scheduling and fine-grained-cpu-orches…
  docs/user-manuals/fine-grained-cpu-orchestration.md
  docs/user-manuals/load-aware-scheduling.md
  sidebars.js
Labels: approved, size/L, lgtm

#60 v0.5 release blog of koordinator
  blog/2022-06-30-release/index.md
Labels: approved, size/L, lgtm

#62 add v0.5 version
  versions.json
Labels: size/XS

#64 fix installation of RuntimeProxy
  docs/designs/runtime-proxy.md
  versioned_docs/version-v0.5/designs/runtime-proxy.md
Labels: size/M, approved, lgtm

#66 Update installation.md
  docs/installation.md
Labels: size/XS, approved, lgtm

#67 Update installation.md
  versioned_docs/version-v0.5/installation.md
Labels: size/XS, approved, lgtm

#68 fix kubelet config for koord-runtime-proxy
  docs/installation.md
  versioned_docs/version-v0.5/installation.md
Labels: size/XS, approved, lgtm
