Repository koordinator-sh/website, pull requests merged in 2023-08, with the labels that each got.

#140 Add memory evict doc
  docs/user-manuals/memory-evict.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/memory-evict.md
  sidebars.js
  static/img/memory-evict.svg
Labels: approved, size/L, lgtm

#136 user manuals: add slo config doc
  docs/user-manuals/slo-config.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/slo-config.md
  sidebars.js
Labels: approved, lgtm, size/XL

#139 Improve the documentation about how to delete over-resource-used pods…
  docs/user-manuals/multi-hierarchy-elastic-quota-management.md
Labels: size/XS, approved, lgtm

#137 best practices: fine-grained cpu orchestration
  docs/best-practices/fine-grained-cpu-orchestration.md
  sidebars.js
Labels: approved, size/L, lgtm

#141 Add cpu evict doc
  docs/user-manuals/cpu-evict.md
  docs/user-manuals/memory-evict.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/cpu-evict.md
  sidebars.js
  static/img/cpu-evict.svg
Labels: approved, size/L, lgtm

#142 Add NRI design and user guide
  docs/designs/nri-mode-resource-management.md
  docs/installation.md
  sidebars.js
  static/img/nri-proposal.png
  static/img/nri.png
  static/img/proxy.png
  static/img/standalone.png
Labels: approved, size/L, lgtm
