Repository koordinator-sh/website, pull requests merged in 2023-05, with the labels that each got.

#133 fix koord-mid priority value
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/architecture/priority.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.1/architecture/priority.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.2/architecture/priority.md
  versioned_docs/version-v0.2/key-designs/priority.md
  versioned_docs/version-v0.4/key-designs/priority.md
  versioned_docs/version-v0.5/architecture/priority.md
  versioned_docs/version-v0.6/architecture/priority.md
  versioned_docs/version-v0.7/architecture/priority.md
  versioned_docs/version-v1.0/architecture/priority.md
  versioned_docs/version-v1.1/architecture/priority.md
Labels: approved, lgtm, size/S

#126 translate resource-reservation.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/resource-reservation.md
Labels: size/M, approved, lgtm

#134 docs: add chinese docs abourt best practice
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.2/best-practices/colocation-of-spark-jobs.md
Labels: approved, size/L, lgtm

#132 Translate i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/pod-migration-job.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/pod-migration-job.md
Labels: size/M, approved, lgtm
