Repository koordinator-sh/website, pull requests merged in 2023-01, with the labels that each got.

#114 Add user manual for Performance Collector with both English and Chinese version
  docs/user-manuals/performance-collector.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/performance-collector.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.1/user-manuals/performance-collector.md
  sidebars.js
  static/img/koordlet-servicemonitor-prometheus.png
  versioned_docs/version-v1.1/user-manuals/performance-collector.md
  versioned_sidebars/version-v1.1-sidebars.json
Labels: approved, lgtm, size/XL

#118 update docs of load-aware scheduling/descheduling and cpu orchestration
  docs/designs/fine-grained-cpu-orchestration.md
  docs/user-manuals/fine-grained-cpu-orchestration.md
  docs/user-manuals/load-aware-descheduling.md
  docs/user-manuals/load-aware-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/fine-grained-cpu-orchestration.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/fine-grained-cpu-orchestration.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/load-aware-descheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/load-aware-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.1/designs/fine-grained-cpu-orchestration.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.1/user-manuals/fine-grained-cpu-orchestration.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.1/user-manuals/load-aware-descheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.1/user-manuals/load-aware-scheduling.md
  sidebars.js
  static/img/low-node-load.png
  versioned_docs/version-v1.1/designs/fine-grained-cpu-orchestration.md
  versioned_docs/version-v1.1/user-manuals/fine-grained-cpu-orchestration.md
  versioned_docs/version-v1.1/user-manuals/load-aware-descheduling.md
  versioned_docs/version-v1.1/user-manuals/load-aware-scheduling.md
  versioned_sidebars/version-v1.1-sidebars.json
Labels: size/XXL, approved, lgtm

#119 update descheduling user manuals
  docs/user-manuals/load-aware-descheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/load-aware-descheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.1/user-manuals/load-aware-descheduling.md
  versioned_docs/version-v1.1/user-manuals/load-aware-descheduling.md
Labels: approved, lgtm

#120 Update version 1.1.1
  docs/installation.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/installation.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.1/installation.md
  versioned_docs/version-v1.1/installation.md
Labels: size/M, approved, lgtm
