Repository koordinator-sh/website, pull requests merged in 2024-04, with the labels that each got.

#168 Doc is out dated, Example not work
  docs/designs/multi-hierarchy-elastic-quota-management.md
Labels: size/XS, approved, lgtm

#167 Update runtime-proxy.md
  docs/designs/runtime-proxy.md
Labels: size/XS, approved, lgtm

#169 add multi quota tree user manual
  docs/user-manuals/capacity-scheduling.md
Labels: approved, size/L, lgtm

#170 feat: add net qos with TerwayQoS
  docs/best-practices/network-qos-with-terwayqos.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/best-practices/network-qos-with-terwayqos.md
Labels: approved, size/L, lgtm

#172 fix be hostapp default cgroup path
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/host-application-qos.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.4/user-manuals/host-application-qos.md
Labels: approved, lgtm, size/S

#173 add terway qos to sidebar
  sidebars.js
Labels: size/XS, approved, lgtm

#175 designs: update the takeover stages in the fine-graned CPU orchestration
  docs/designs/fine-grained-cpu-orchestration.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/best-practices/colocation-of-hadoop-yarn.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/fine-grained-cpu-orchestration.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/memory-evict.md
Labels: size/M, approved, lgtm

#165 fix shard-weight position error
  docs/user-manuals/capacity-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/multi-hierarchy-elastic-quota-management.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/multi-hierarchy-elastic-quota-management.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.1/user-manuals/multi-hierarchy-elastic-quota-management.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.2/user-manuals/multi-hierarchy-elastic-quota-management.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.3/user-manuals/multi-hierarchy-elastic-quota-management.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.4/user-manuals/multi-hierarchy-elastic-quota-management.md
  versioned_docs/version-v0.7/user-manuals/multi-hierarchy-elastic-quota-management.md
  versioned_docs/version-v1.0/user-manuals/multi-hierarchy-elastic-quota-management.md
  versioned_docs/version-v1.1/user-manuals/multi-hierarchy-elastic-quota-management.md
  versioned_docs/version-v1.2/user-manuals/multi-hierarchy-elastic-quota-management.md
  versioned_docs/version-v1.3/user-manuals/multi-hierarchy-elastic-quota-management.md
  versioned_docs/version-v1.4/user-manuals/capacity-scheduling.md
Labels: approved, lgtm, size/S

#174 fix doc: filter node which updateTime since now greater than nodeMetricExpirationSeconds
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/load-aware-scheduling.md
Labels: size/XS, approved, lgtm

#176 website: modify website footer to meet CNCF onboarding requirement
  docusaurus.config.js
  static/img/cncf-color.svg
Labels: approved, size/L, lgtm
