Repository koordinator-sh/website, pull requests merged in 2025-02, with the labels that each got.

#194 feat: add KEP for NodeResourceFitPlus and ScarceResourceAvoidance
  docs/designs/node-resource-fit-plus-scoring.md
  docs/user-manuals/node-resource-fit-plus-scoring.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/node-resource-fit-plus-scoring.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/node-resource-fit-plus-scoring.md
  sidebars.js
  static/img/node-resource-fit-plus-scoring-cn.png
  static/img/node-resource-fit-plus-scoring-en.png
  yarn.lock
Labels: approved, lgtm

#184 update gang-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/gang-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/gang-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.1/designs/gang-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.2/designs/gang-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.3/designs/gang-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.4/designs/gang-scheduling.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.5/designs/gang-scheduling.md
Labels: approved, lgtm, size/S

#185 add best practice docs for developing custom descheduler plugins
  docs/best-practices/develop-custom-deschedule-plugins.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/best-practices/develop-custom-deschedule-plugins.md
  sidebars.js
Labels: approved, size/L, lgtm

#196 fix: update NodeResourceFitPlus KEP
  docs/user-manuals/node-resource-fit-plus-scoring.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/node-resource-fit-plus-scoring.md
Labels: approved, lgtm

#192 Best practice: GPU & RDMA Joint Allocation
  docs/best-practices/gpu-and-rdma-joint-allocation.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/best-practices/gpu-and-rdma-joint-allocation.md
  sidebars.js
  static/img/device-topology-and-network-communication.jpg
  static/img/gpu-rdma-joint-allocation.jpg
  static/img/rdma-nic-topo.png
Labels: approved, lgtm
